---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by White.
--- DateTime: 2023/1/9 20:39
---

if redis.call('get', KEYS[1] == ARGV[1])
then
    return redis.call('del', KEYS[1])
end
return 0