#分组管理配置文件
spring:
  profiles:
    group:
      "dev": devDB
      "test": testDB
      "redis": redis
    active: dev

  #配置redis
  redis:
    host: 192.168.93.130
    port: 6379

  #配置缓存
  cache:
    type: redis
    cache-names: linux


#配置端口
server:
  port: 80


#配置mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: redis_05.enums
  global-config:
    db-config:
      id-type: auto