---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by White.
--- DateTime: 2023/1/9 11:34
---

--      lua学习第五章 面向对象

-- 一、创建一个animal对象,并修改方法
animal = { name = 'tom', age = 5, eat = function (self,temp)
    print(self.name.."正在"..temp.."得吃东西")
end }

--添加方法方式1
--  self参数含义：相当于this
animal.bark = function(self,voice)
    print(self.name.."正在"..voice.."叫")
end

--添加方法方式2
--  使用":”则会自动调用self,但只能以这种方式定义方法
function animal:sleep(temp)
    print(self.name.."正在"..temp.."得睡觉")
end

--调用方法
animal.bark(animal,"喵喵")


--定义对象animal2
animal2 = animal
animal2.name="斯派克"
--设置animal为nul
animal=nil
--调用方法
print(animal2.bark(animal2,"汪汪"))
print(animal2:sleep("呼呼"))