---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by White.
--- DateTime: 2023/1/9 11:35
---

--      lua学习第五章 面向对象

-- 二、创建一个类
Animal = { name = 'no_name', age = 0 }

--为该类添加无参构造器
function Animal:new()
    --创建一个空表
    local a = {}

    --将空表与元表关联
    setmetatable(a, {
        --为a表指定元表为基础类表
        __index = self
    })

    --返回新表
    return a
end

--为该类添加有参构造器（参数为table）
function Animal:new(obj)
    local a = {}
    if type(obj) == "table" then
        a = obj
    else
        a = {}
    end
    setmetatable(a, {
        __index = self
    })
    return a
end

--添加方法
function Animal:bark(voice)
    print(self.name .. "正在" .. voice .. "叫")
end

--创建对象
animal1 = Animal:new()
animal1.name = "tom"
animal2 = Animal:new()
--判断是否为同一个对象
print(animal1 == animal2)
--调用方法
animal1:bark("喵喵")
animal2:bark("吱吱")

--使用有参构造器创建对象
animal3 = Animal:new({ name = "斯派克" })
print(animal3:bark("汪汪"))

--  三、类的继承
--为Animal类创建子类Cat
cat = Animal:new()
cat.eyes = "蓝眼睛"
cat.type = "波斯猫"

--实例化cat对象
tomcat = cat:new()
tomcat.name = "tom"
print(tomcat.name.."是"..cat.eyes.."的"..cat.type)
