---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by White.
--- DateTime: 2023/1/9 9:15
---

--    lua学习——第四章 元表与元方法
--三、导入外部元表

--定义一个混合结构
emp = { "北京", name = "张三", age = 23, '上海', '广州', '深圳', 15 }

--导入外部元表
require("lua_04_Metatable_module")

--将普通表和元表关联
setmetatable(emp,meta)

--添加新的元方法
meta.__index = function(table, key)
    return "通过["..key.."] 访问的元素不存在" --通过[10] 访问的元素不存在
end

--测试方法
print(emp[8])
empsum = emp+3
print(empsum)
emp2 = emp(3,"-hi")
print(emp2)
