---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by White.
--- DateTime: 2023/1/9 8:56
---

--    lua学习——第三章 使用模块

-- !!！注意模块名应和文件名一致

-- 1.导入模块，使用变量接收
rect = require("lua_03_Module_rectangle")

-- 2.调用模块中的函数
print(rectangle.pi)
print(rectangle.girth(3))
print(rectangle.area(3))

print(rect.pi)
print(rect.girth(3))
print(rect.area(3))

-- 3.调用模块中的无关变量、函数
print(goldenRatio)
print(maxArea(3, 4))