---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by White.
--- DateTime: 2023/1/9 8:43
---

--    lua学习——第三章 定义模块

-- !!！注意模块名应和文件名一致

-- 1.定义一个模块-------------------------
-- 声明一个模块
rectangle = {}

-- 为模块添加变量
rectangle.pi = 3.14

-- 为模块添加函数（求周长）
function rectangle.girth(r)
    return 2*rectangle.pi*r
end

-- 以匿名函数方式求面积
rectangle.area=function(r)
    return rectangle.pi*r^2
end


-- 定义一个全局变量（与模块无关）
goldenRatio =0.618

--定义一个无关的局部函数，外部不能导入
local function f1(a,b)
    return (a+b)*2
end

--定义一个无关的函数
function maxArea(a,b)
    if a>=b then
        return rectangle.pi*a^2
    else return rectangle.pi*b^2
    end
end


-- 返回模块
return rectangle
