---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by White.
--- DateTime: 2023/1/9 14:33
---

--      lua学习第七章 文件IO

--  一、静态函数
-- 1.io.open()：以指定模式打开文件
print("--一、静态函数读取文件")
file1 = (io.open("lua_07_info.properties", "r"))

--  2.io.input()：指定要读取的文件
io.input(file1)

--  3.读取一行数据
line = io.read()
--一直读取文件
while line ~= nil do
    print(line)
    line = io.read()
end

-- 4.关闭文件
io.close(file1)


--写入数据
--   使用io.write()，容易写很多奇怪数据
--print("--一、静态函数写入文件")
--file2 = (io.open("lua_07_info.properties", "a"))
--
--io.input(file2)
--指定要写入的文件
--io.output(file2)
--将指定的数据data写入到io.output中指定的输出文件
--io.write("\ncompany=huawei\n")
--io.close(file2)


-----------------------------------------------------------
--  二、实例函数
--  1.读取文件
print("--二、实例函数读取文件")
-- 1.io.open()：以指定模式打开文件
file3 = (io.open("lua_07_info.properties", "r"))

--  2.file:read()：读取一行数据
line = file3:read()
--一直读取文件
while line ~= nil do
    print(line)
    line = file3:read()
end

-- 4.关闭文件
io.close(file3)


----  2.写入文件
--print("二、实例函数写入文件")
--
--file4 = (io.open("lua_07_info.properties", "a"))
--
--file4:write("depart=market")
--
--io.close(file4)


------------------------------------------------------
--  3.file:seek()
print("-- 二、实例函数指针")
file5 = io.open("lua_07_numbers.txt")

--查看指针位置
pos1 = file5:seek()
print(pos1) --0：位置0表示文件第一个位置的前面位置。

--读取一行
line = file5:read()
pos1 = file5:seek()
print(pos1) --7：行结束符占两个位置

--返回起始位置
pos1 = file5:seek("set") --set：定位到起始位置
print(pos1) --0

--返回起始位置
pos1 = file5:seek("set", 2) --set：定位到起始位置后的第二个位置
line = file5:read()
print(pos1, line) --0 345

--定位到结尾处
pos1 = file5:seek("end") --end：定位到结束位置
print(pos1) --14



